### ISSUE TITLE
The module dependency 'os' does not exist when used in React Native

### ISSUE THREAD

**Issue by geocachingsyntaxerror** [Azure/ms-rest-js#10]
I'm using AutoRest to generate a typescript rest client and converting that to ES6 to be used in a React Native app. The generated client relies on the 'ms-rest-js' runtime which relies on the nodejs module 'os' to hydrate the operating system info on the user agent string in the MsRestUserAgentFilter. Unfortunately the 'os' module is not implemented in React Native as far as I'm aware. 

I can pull in the nodejs 'os' module to get the bundler to succeed but unfortunately 'detect-node' returns true when running within React Native. This causes code to execute against the 'os' module but it's not implemented within React Native which yields a runtime error at line 23 of msRestUserAgentFilter.ts:
`const osInfo = '(${os.arch()}-${os.type()}-${os.release()})';`

If I use a debugger and set IsNode to false, everything works as expected.

When I manually replace the module dependency 'os' with '[react-native-os'](https://github.com/PeelTechnologies/react-native-os) in this scenario, everything behaves as expected. I spent a few hours attempting to alias require('os') to require('react-native-os') in my build but couldn't get it working. It's also hacky.

React Native may fall outside of intended use cases, but I'd be much obliged if 'ms-rest-js' (or an alternative package) could work in React Native without modification on my end, either by relying on the appropriate dependency ('react-native-os' vs 'os'), or by optionally bypassing/overriding the operating system info on the user agent string.

![screen shot 2018-01-23 at 4 59 44 pm](https://user-images.githubusercontent.com/8315604/35309462-8805aa90-0061-11e8-9e61-ef3caf42e616.png)

**Comment by amarzavery** [comment]
@geocachingsyntaxerror - Thanks for reporting this issue.
Can you pull the changes I made in #11 and verify whether that works for you?

**Comment by geocachingsyntaxerror** [comment]
I pulled your detect branch and it worked as expected in react-native; isNode returns false as expected. Thank you.
