### ISSUE TITLE
Base Path Replaced

### ISSUE THREAD

**Issue by ProTip** [Azure/ms-rest-js#113]
The way the new URL Builder works/is utilized causes the base path to be completely replaced with the request path:

baseUrl: ```localhost:8080/api/23```
path: ```/user/list```
request: ```localhost:8080/user/list```

desired request: ```localhost:8080/api/23/user/list```

**Comment by ProTip** [comment]
I'm not using this directly myself but via ```autorest.typescript```. Should I file a bug with that project to supply the full path in the request options?

**Comment by daschult** [comment]
No, this repo will do fine as a place for this issue. Don't worry about creating an issue on `autorest.typescript`.
Can you provide me with a link to your swagger file? Looking at that might be able to help me provide a better solution.

**Comment by ProTip** [comment]
You bet: https://github.com/ProTip/openapi/blob/master/rundeck.yaml

Although I am currently, as is a typical use case, supplying a baseUri via the constructor.

**Comment by daschult** [comment]
Thanks for pointing me to your swagger. You've definitely identified an issue with the URLBuilder that I'll start working on right away.

**Comment by daschult** [comment]
I'll update this issue when I have a PR out that fixes this problem.

**Comment by daschult** [comment]
@ProTip I just mered a PR that should resolve this issue. Can you regenerate your TypeScript code and see if your problem goes away?

**Comment by ProTip** [comment]
LGTM!
