### ISSUE TITLE
Response data not parsed when content type includes encoding

### ISSUE THREAD

**Issue by ProTip** [Azure/ms-rest-js#114]
I'm getting back a content type that includes encoding: ```application/json;charset=UTF-8```.

This is failing the check in the axios client on ```@preview```:
```js
else if (contentType === "application/json" || contentType === "text/json" || !contentType)
```

I do not get parsed data back :|

**Comment by RikkiGibson** [comment]
perhaps we should use `contentType.split(";")[0]`?

**Comment by daschult** [comment]
I think it makes more sense to check each element of the split array. As far as I know, `application/json;charset=UTF-8` is equivalent to `charset=UTF-8;application/json`. Even though one is more likely than the other, we should still be able to handle both scenarios.

**Comment by amarzavery** [comment]
or contentType.startsWith("application/json")

**Comment by amarzavery** [comment]
[string.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) would be a better option.
