### ISSUE TITLE
Add test coverage reporter in all the runtimes

### ISSUE THREAD

**Issue by amarzavery** [Azure/ms-rest-js#118]
[nyc](https://www.npmjs.com/package/nyc) is a good reporter and integrates well with typescript. It gives us good test coverage report.
```
"scripts": {
  "test": "nyc mocha ..."
   . . . 
}
```

**Comment by daschult** [comment]
Oh, yes please. I would love to use nyc in our projects. I use it in my personal development and test coverage is a wonderful tool.

**Comment by daschult** [comment]
I have a branch where this is working in ms-rest-js, but it doesn't work with the test server that we have set up to run during our unit tests. I'll need to talk to @RikkiGibson about if there is a different way to integrate the test server with the tests.

**Comment by RikkiGibson** [comment]
So is the issue that we won't get coverage reporting on the test server itself? Or some interaction with the test server is preventing coverage from working on the ms-rest-js code that we ship?

**Comment by daschult** [comment]
Some kind of iteration with the test server prevents the tests from finishing before timeout. The tests run and we do get coverage, but the test results (pass or fail) don't show up and a single failure is output to the console saying that "before hook" failed with a timeout error. I don't even know how to begin debugging this. I figured I'd just talk to you about it when you got in today, or you can feel free to reproduce the problem your own machine by checkout out my branch: https://github.com/Azure/ms-rest-js/tree/daschult/coverage.

**Comment by RikkiGibson** [comment]
Sounds good! I'll be in today.

**Comment by daschult** [comment]
We couldn't figure out how to make this work in ms-rest-js, but I have since gotten this to work in ms-rest-azure-js, so I'm going to call this issue done for now.
