### ISSUE TITLE
parsedBody is undfined when a charset is provided

### ISSUE THREAD

**Issue by KyleGobel** [Azure/ms-rest-js#120]
Looking into some problems I'm having.  Any request I make with autorest.typescript always returns undefined.

The reason I think* is that my server sets the content type to this:

```
Content-Type: application/json; charset=utf-8
```

Looking into your axiosClient you seem to be checking for exactly 'application/json' in order to set the `parsedBody` property of the response.

I know little about the rules of how content-type needs to be formatted.  Is this a mistake on my server side, or is the axiosClient just being a little too stingy?

**Comment by RikkiGibson** [comment]
Duplicate of #114. We're in the wrong here-- will be fixing it to do a `.contains()` check or similar :)

**Comment by KyleGobel** [comment]
Ahh, my bad for not searching/looking at top issues first.  Thanks.
