### ISSUE TITLE
Increase isomorphic-xml2js version to 0.1.3 to support create-react-app.

### ISSUE THREAD

**Issue by bernarden** [Azure/ms-rest-js#145]
Would it be possible to increase isomorphic-xml2js version to 0.1.3 so that `react-scripts build` command will start working? 

![2018-06-22 15_27_17-administrator_ windows powershell](https://user-images.githubusercontent.com/12289537/41756450-ce420810-7630-11e8-8ad7-d4b7a275c564.png)
> Note: isomorphic-xml2js started targeting ES5 from version: 0.1.3

**Comment by RikkiGibson** [comment]
Weird, I thought I already did this.

**Comment by RikkiGibson** [comment]
Updated the dependency version and published a new ms-rest-js version. Installing `ms-rest-js@latest` should do the trick now. Thanks for letting us know!

**Comment by bernarden** [comment]
Thank you! This works for me now. =)

**Comment by amarzavery** [comment]
That is cool. @bernarden - We want to generate a react-native app from a swagger specification some day. If possible can you share the project link where you are using ms-rest-js in your react app? We would love to see how this library is used in the react app.

**Comment by bernarden** [comment]
@amarzavery Unfortunately, this is used in a company's IP, so I can't share the code. Sorry.
