### ISSUE TITLE
Versions on npm

### ISSUE THREAD

**Issue by chicoxyzzy** [Azure/ms-rest-js#175]
Hi. npm says that latest version is 0.12.293. However it's possible to install 0.16.371 which I believe is actual latest version.

**Comment by RikkiGibson** [comment]
We've been relying pretty heavily on our automated `@preview` publishing. Perhaps we should come up with a cadence for promoting these to `@latest`. (Every other Thursday perhaps?)

**Comment by daschult** [comment]
We've done away with the preview tag and are now only publishing to the latest tag.
