### ISSUE TITLE
Deserialize response headers as case-insensitive

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/ms-rest-js#195]
@XiaoningLiu has pointed out that some browsers use different casing conventions for header names and this prevents some response headers from deserializing properly.

HTTP header names are specified as case insensitive, so let's do the following to solve this:
- Convert header names on the response to lower case before deserializing
- Make serializedName on the response headers mapper always lower case (I think we already do this)

**Comment by daschult** [comment]
Does @XiaoningLiu have a case that is failing because of this? I'm confused because the HttpHeaders class already [gets HttpHeader values based on a case-insensitive name](https://github.com/Azure/ms-rest-js/blob/master/lib/httpHeaders.ts#L7). Where in the code is the sensitivity of the header name making a difference?

**Comment by RikkiGibson** [comment]
This is the key line of code I think.

https://github.com/Azure/ms-rest-js/blob/master/lib/policies/deserializationPolicy.ts#L123

Also attaching Xiaoning's screenshots:

**Firefox** (exhibits the problem)
![image](https://user-images.githubusercontent.com/5833655/44475760-bdcc1900-a5ea-11e8-953f-1ea83175ff6a.png)

**Chrome** (works as expected)
![image](https://user-images.githubusercontent.com/5833655/44475776-c7ee1780-a5ea-11e8-97bf-6ae718d2de40.png)

**Comment by daschult** [comment]
Ah, I see. It's because we're getting the raw headers. That would make it case-sensitive for sure.

**Comment by RikkiGibson** [comment]
Yeah, so I think just setting all the key names to lowercase on that object before passing it to `deserialize()` will do the trick.

Maybe we can add a backlog item for automated Firefox testing. That can be done on Travis, I believe.

The trouble is that it's tricky to automate tests on all browsers without pulling in a service like Sauce Labs.
