### ISSUE TITLE
Cannot abort a download Readable Stream in Node.js with an AbortSignal

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/ms-rest-js#204]
For a request returning a ReadableStream, the abortSignal only works before headers returned. After that, the abortSignal cannot work to abort the returned readableStream.

Not sure it's a bug of axios or by design. But the abortSignal should be able to abort a readableStream and close the TCP connection.

**Comment by ramya-rao-a** [comment]
The storage packages have moved on to using `@azure/core-http` rather this package. So, closing.
Please log a new issue in https://github.com/azure/azure-sdk-for-js if you see the same in the new packages
