### ISSUE TITLE
Cannot read property 'split' of undefined occurred in deserializing the responseBody

### ISSUE THREAD

**Issue by abhishekgoenka** [Azure/ms-rest-js#212]
I am getting an error while deserializing response. `modelProps[key].serializedName` is undefined. Is this supposed to be happening?
![image](https://user-images.githubusercontent.com/14522198/44978575-ac8af100-af88-11e8-9161-802a5393a8d5.png)
![image](https://user-images.githubusercontent.com/14522198/44978623-caf0ec80-af88-11e8-9572-98fd23276ab7.png)

**Comment by abhishekgoenka** [comment]
I found the solution. You need to make following changes in `lib\serializer.ts` file
![image](https://user-images.githubusercontent.com/14522198/44991951-6f882400-afb3-11e8-934f-e8d72d487a59.png)

![image](https://user-images.githubusercontent.com/14522198/44991962-77e05f00-afb3-11e8-93d7-fac3c935b92f.png)

Can you check-in the changes, so I can take the new build?

**Comment by RikkiGibson** [comment]
Please ensure you have the latest preview of autorest.typescript and ms-rest-js.

Also would be helpful to know if you have `additionalProperties: true` anywhere in your swagger, as that's a pending feature.

**Comment by abhishekgoenka** [comment]
I am on version **0.21.406**. Is it fixed in latest preview? I don't have access to api code but generated json does have `additionalProperties` attribute

**Comment by RikkiGibson** [comment]
Unlikely to have changed in the latest preview. :)

Please feel free to open the PR, I'm sure it'll be useful. I will try and use it to implement Azure/autorest.typescript#232

**Comment by abhishekgoenka** [comment]
Pull request submitted : #214

**Comment by RikkiGibson** [comment]
Published in ms-rest-js@0.21.412. Thanks again.
