### ISSUE TITLE
Browser build should export global under conventional name

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/ms-rest-js#224]
Right now we just create the global `msRest` when bundling for the browser.

We'd like to use a shared namespace for Azure libraries bundled for the browser, so instead would use:

`Microsoft.Azure.MsRest`

@bterlson

**Comment by bterlson** [comment]
It's important to do this soon as this is technically a breaking change. Dependent packages that don't wish to bundle this library in-package (a great idea considering its size 😄) they need to map the module import specifier to a global name.

**Comment by RikkiGibson** [comment]
We talked it over and we're sticking with the browser global names `msRest`, `msRestAzure`, `msAuth` because:

1. users are very familiar with the `msRest` library var
2. as core libraries they don't quite fit in the same category as the Azure SDKs
