### ISSUE TITLE
Fail deserialization of malformed base64 in nodejs

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/ms-rest-js#227]
Right now, `Buffer.from(str, 'base64')` will act as if successful even if the string was not in base64 format. The browser's `atob` will throw an error in these cases.

In order to handle the **getByteInvalid** autorest.testserver scenario, we should consider adding a validation or an alternate base64 decoder which will fail on the malformed string.

**Comment by ramya-rao-a** [comment]
Closing this as separate efforts are underway to get to test coverage for autorest.typescript
