### ISSUE TITLE
Ensure publishing of dependent libs upon major bump

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/ms-rest-js#230]
We have occasional problems where we publish a new major version e.g. of ms-rest-js but don't publish a new major version of a dependent lib like ms-rest-azure-js or ms-rest-nodeauth.

As long as the versions on npm are in this state, proper usage of these related libraries impossible, so let's come up with an automation of some kind to publish new versions of the dependent libraries upon publish of a new major of a core library.

Let's have this issue be concerned with the libraries with common dependencies:

- ms-rest-js
- ms-rest-azure-js
- ms-rest-nodeauth
- ms-rest-browserauth (pending)

azure-env should not be affected.

This will probably be solved in the azure-sdk-for-js itself using lerna. Over there we can monolithically update a dependency, update the package versions and publish fairly easily.

**Comment by ramya-rao-a** [comment]
`@azure/ms-rest-js` is currently in maintenance mode with no new features being added and taking only bug fixes. We are moving active development efforts in the azure-sdk-for-js repo on `@azure/core-http` that will power the next generation of the Azure packages. Therefore, closing this issue.
