### ISSUE TITLE
sub path in baseUri is lost

### ISSUE THREAD

**Issue by bluecamel** [Azure/ms-rest-js#236]
I'm using a client generated with `autorest.typescript`.  As far as I can tell, this is not an issue with that project, but with this client.  When a `baseUri` includes a subpath (e.g. `https://some.domain.com/subPath`), the operation path overrides the sub path and the client tries to instead hit `https://some.domain.com/operationPath`.

**Comment by bluecamel** [comment]
The override happens here: https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts#L203

**Comment by daschult** [comment]
The PR that I referenced should fix this problem. If you update your generated package.json to reference [the most recently published preview version of ms-rest-js](https://www.npmjs.com/package/ms-rest-js/v/0.22.429), then that should solve your problem.
Thanks for pointing this out.

**Comment by bluecamel** [comment]
Thanks so much!
