### ISSUE TITLE
Issue with @types/node version

### ISSUE THREAD

**Issue by bluecamel** [Azure/ms-rest-js#241]
We're using the client in projects that are pinned to @types/node@8+ as we're running on node 8 LTS until we can switch to node 10.  This project specifies a version of @types/node@9+, which breaks our compile.  We've currently fixed this by forking the project and setting the version to "*" so that our package overrides the version.

Would this be an acceptable solution for the project as a whole or is there a reason that you're using a non-LTS version?  If so, I'm happy to provide the (extremely complicated 🤣 ) PR.

Thanks!

**Comment by amarzavery** [comment]
Yes, it should depend on the latest version of @types/node. Moreover all the `@types/*` packacges should always be in `"devDependencies"`.In this way it does not enforce them on the consumer of the package. The consumer can choose to  install different versions in their dev dependencies.
