### ISSUE TITLE
Create a default Aborter for node http client

### ISSUE THREAD

**Issue by amarzavery** [Azure/ms-rest-js#261]
ms-rest-js does support aborting requests. In the browser, our default http browser client is xhr. Xhr supports aborting requests out of the box. If customers are using the default http browser client then they need worry about aborting requests.

However, for node.js as of today they need to implement their own aborter that satisfies the AbortSignalLike Interface. Well that is a good starting point. It would be better if implement the default node.js aborter and set it as the default one. If the customer wishes to provide their own aborter then they should still be able to do that.

Blob Storage has implemented an aborter for node.js over [here](https://github.com/Azure/azure-storage-js/blob/master/blob/lib/Aborter.ts). Please take a look at that to implement the default aborter.

**Comment by justinwilaby** [comment]
#169 along with this issue seems to justify standardizing on [node-fetch](https://www.npmjs.com/package/node-fetch#request-cancellation-with-abortsignal).

**Comment by ramya-rao-a** [comment]
`@azure/ms-rest-js` is currently in maintenance mode with no new features being added and taking only bug fixes. We are moving active development efforts in the azure-sdk-for-js repo on `@azure/core-http` that will power the next generation of the Azure packages where we are indeed using node fetch and a standard `@azure/abort-controller`. Therefore, closing this issue.
