### ISSUE TITLE
Version 1.0.465 removed addUserAgentInfo from ServiceClient which is a breaking change

### ISSUE THREAD

**Issue by sgellock** [Azure/ms-rest-js#276]
We generated code using 1.0.455.  This generated code is crashing when our customers install botbuilder, as pulls in the 1.0.465.

Looks like this method was removed with the following commit:
https://github.com/Azure/ms-rest-js/commit/523b891b4de679542f725a96b8c896432b44ecc4#diff-3b5c4e8e88ea4820a88a9584a654fe8cL144

**Expected behavior**
Following semver rules, patch versions should not be breaking.

**Comment by daschult** [comment]
Hi sgellock.
Yes, this was a mistake on our side. We were under the impression that the addUserAgentInfo() method was only called internally.
If you are interested in changing the user agent that a ServiceClient adds to outgoing requests, then I recommend using the [ServiceClientOptions.userAgent property](https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts#L76).
If you don't care about changing the user agent header, then I'd recommend running "autorest --reset" and then trying to regenerate. I just updated the latest version of our TypeScript generator and that should solve the problem.

**Comment by daschult** [comment]
Related to https://github.com/Azure/autorest.typescript/issues/386.

**Comment by sgellock** [comment]
We pinned to an earlier version that didn’t have the breaking change and published new versions of our bits.

We believe your suggestion will work, but we haven’t tried it.

**Comment by daschult** [comment]
I'm going to close this issue. Feel free to reopen if my proposed solution doesn't work.

**Comment by tomlm** [comment]
This is not a solution because it BREAKS existing clients that depend on this library.

you can't do this, it is unprofessional.  If you are going to break it you need to do a major version change.

**Comment by daschult** [comment]
For future references, in https://github.com/Azure/ms-rest-js/pull/313 we changed ServiceClientOptions.userAgent to be either a string or a function that takes in the defaultUserAgent string and then returns the string that the ServiceClient will use. This should enable previous scenarios where people simply wanted to append to the existing user-agent string, and it should also enable other scenarios too (prepending, inserting, or whatever else someone wants to do with the defaultUserAgent string).
