### ISSUE TITLE
msRestUserAgentPolicy.js errors - cannot resolve "os"

### ISSUE THREAD

**Issue by adha-admin** [Azure/ms-rest-js#281]
**Package Version**: 1.1.0_
- [ ] **nodejs**
   - **nodejs version**: ______
   - **os name/version**: _____
- [ ] **browser**
    - **name/version**: ____
**Describe the bug**

**To Reproduce**
1. Updating our ms-rest-js package from 1.0.x to 1.1.0
changed
from
"ms-rest-js": "^1.0.x",
to
"@azure/ms-rest-js": "^1.1.0",
in my package.json file

**Expected behavior**
It worked before I updated this package

**Screenshots**
I get this error
I do npm run serve on my angular website and get this error
ERROR in ./node_modules/@azure/ms-rest-js/es/lib/policies/msRestUserAgentPolicy.js
Module not found: Error: Can't resolve 'os' in 
....\ClientApp\node_modules\@azure\ms-rest-js\es\lib\policies'

which seems to indicate the import statement is failing
import * as os from "os";

**Additional context**
HELP

**Comment by bricejar** [comment]
It seems that we should not expect ms-rest-js and @azure-ms-rest-js to be identitical even with the same version number

**Comment by daschult** [comment]
I'm a little confused. Is there actually an issue here, or is everything fine now?

**Comment by adha-admin** [comment]
Still doesnt work after clearing all:
- npm node modules from \users\...\appdata\roaming\npm and npm-cache
- cleared the autorest and reinstalled: \users\...\.autorest:
csharp@2.3.82
modeler@2.3.51
modeler@2.3.55
typescript@2.0.683
autorest-core@2.0.4289

package.json: 		"@azure/ms-rest-js": "^1.1.0",
in my typescript client:
import { TokenCredentials } from '@azure/ms-rest-js';

I regen my client but still get error even though the file exists:

ERROR in ./node_modules/@azure/ms-rest-js/es/lib/policies/msRestUserAgentPolicy.js
Module not found: Error: Can't resolve 'os' in 'D:\Phils\GIT\Projects\sra\src\Sra.Web\ClientApp\node_modules\@azure\ms-rest-js\es\lib\policies'

Which DOES EXIST:

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
export function getDefaultUserAgentKey() {
    return "x-ms-command-name";
}
export function getPlatformSpecificData() {
    var navigator = window.navigator;
    var osInfo = {
        key: "OS",
        value: (navigator.oscpu || navigator.platform).replace(" ", "")
    };
    return [osInfo];
}
//# sourceMappingURL=msRestUserAgentPolicy.browser.js.map

**Comment by daschult** [comment]
Okay, I have two things for you to try:

1. See if changing @azure/ms-rest-js to 1.1.1 solves the problem. We did have a bundling bug that we fixed just a couple of days ago that seems related to this issue. If this doesn't solve the problem, then:
2. See if adding @types/node to your devDependencies solves the problem. If it does, then I'll move @types/node from our devDependencies to our dependencies.

**Comment by Worminator30** [comment]
Can confirm this is an issue. I am getting the same problem described in the original submission. I have also tried all of the steps suggested.

**Comment by adha-admin** [comment]
Hi there,
Tried the version 1.1.1 - same error
Tried adding the @types/node and still the error
npm install @types/node  --save-dev
Also tried on another developers machine

**Comment by daschult** [comment]
Okay, thanks for giving that a try. Can you post a copy of how your code consumes the ms-rest-js package (specifically the lines where you're importing from ms-rest-js in your code)? Did you use AutoRest to generate a TypeScript client?

**Comment by adha-admin** [comment]
Thanks for looking into this for me. Details requested below:

This is the command I use to autogenerate the client:

autorest --typescript --input-file=http://localhost:61817/ApiCore/swagger/v1/swagger.json --output-folder=gentypescript --add-credentials --package-name="apiCore" --package-version="1.0" --license-header=MICROSOFT_MIT_NO_VERSION

The Output:
AutoRest code generation utility [version: 2.0.4283; node: v10.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\x\.autorest\@microsoft.azure_autorest-core@2.0.4289\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4289)
   Installing AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51)


The Output from autorest --version:

AutoRest code generation utility [version: 2.0.4283; node: v10.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

Showing All Installed Extensions
 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4289     C:\Users\x\.autorest\@microsoft.azure_autorest-core@2.0.4289
 extension  @microsoft.azure/autorest.csharp         2.3.82       C:\Users\x\.autorest\@microsoft.azure_autorest.csharp@2.3.82
 extension  @microsoft.azure/autorest.modeler        2.3.51       C:\Users\x\.autorest\@microsoft.azure_autorest.modeler@2.3.51
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\x\.autorest\@microsoft.azure_autorest.modeler@2.3.55
 extension  @microsoft.azure/autorest.typescript     2.0.683      C:\Users\x\.autorest\@microsoft.azure_autorest.typescript@2.0.683

**Comment by daschult** [comment]
Can you try running `autorest --reset` and then regenerating? We have a [newer version of the TypeScript generator](https://www.npmjs.com/package/@microsoft.azure/autorest.typescript/v/2.1.0) out and it would be nice if telling autorest to refresh its generator cache fixes this problem.

**Comment by adha-admin** [comment]
Have you changed anything? I get the same error after doing an autorest --reset ...
Versions below:

AutoRest code generation utility [version: 2.0.4283; node: v10.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4289     C:\Users\philipwilford\.autorest\@microsoft.azure_autorest-core@2.0.4289
 extension  @microsoft.azure/autorest.csharp         2.3.82       C:\Users\philipwilford\.autorest\@microsoft.azure_autorest.csharp@2.3.82
 extension  @microsoft.azure/autorest.modeler        2.3.51       C:\Users\philipwilford\.autorest\@microsoft.azure_autorest.modeler@2.3.51
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\philipwilford\.autorest\@microsoft.azure_autorest.modeler@2.3.55
 extension  @microsoft.azure/autorest.typescript     2.0.683      C:\Users\philipwilford\.autorest\@microsoft.azure_autorest.typescript@2.0.683

**Comment by daschult** [comment]
Too bad that those options didn't solve the problem.
How're you referencing your generated client in your application? Our generated clients are intended to be standalone packages that are imported by your applications. If you generate the client using `--generate-metadata=true` then it will generate several files that help in creating a package for your generated client. One of those generated metadata files is a `rollup.config.js` file ([such as this one](https://github.com/Azure/azure-sdk-for-js/blob/master/packages/%40azure/arm-storage/rollup.config.js)) and a `package.json` file ([such as this one](https://github.com/Azure/azure-sdk-for-js/blob/master/packages/%40azure/arm-storage/package.json)). In the `package.json` file you'll see that the `main` property is set to `dist/<your-package-name>.js`. This is the browser-ready build that is created by your rollup configuration file. In the browser scenario, we assume that you have already imported the `ms-rest-js` package as shown [here](https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure/arm-storage#sample-code-1).
Since I haven't seen how you're referencing your generated client or ms-rest-js from your actual code files, I can't know for sure what you need to do, but I'm hoping that adding `--generate-metadata=true` to your generation step might provide a few extra clues.

**Comment by daschult** [comment]
I'm going to assume that my previous instructions were enough to help you out. Feel free to reopen this issue if the problem persists and you're still stuck.

**Comment by adha-admin** [comment]
Hi there,
I still get the same error and cannot see any info in those extra files it generates.

autorest --typescript --use=@microsoft.azure/autorest.typescript@2.1.0 --generate-metadata=true --input-file=http://localhost:61817/SraWebApiCore/swagger/v1/swagger.json --output-folder=gentypescript --add-credentials --package-name="sra" --package-version="1.0" --license-header=MICROSOFT_MIT_NO_VERSION

rollup.config.js
====
import rollup from "rollup";
import nodeResolve from "rollup-plugin-node-resolve";
import sourcemaps from "rollup-plugin-sourcemaps";

/**
 * @type {rollup.RollupFileOptions}
 */
const config = {
  input: "./esm/sraAPI.js",
  external: [
    "@azure/ms-rest-js",
    "@azure/ms-rest-azure-js"
  ],
  output: {
    file: "./dist/sra.js",
    format: "umd",
    name: "Sra",
    sourcemap: true,
    globals: {
      "@azure/ms-rest-js": "msRest",
      "@azure/ms-rest-azure-js": "msRestAzure"
    },
    banner: `/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */`
  },
  plugins: [
    nodeResolve({ module: true }),
    sourcemaps()
  ]
};

export default config;


package.json
=========
{
  "name": "sra",
  "author": "Microsoft Corporation",
  "description": "SraAPI Library with typescript type definitions for node.js and browser.",
  "version": "1.0",
  "dependencies": {
    "@azure/ms-rest-js": "^1.1.0",
    "tslib": "^1.9.3"
  },
  "keywords": [
    "node",
    "azure",
    "typescript",
    "browser",
    "isomorphic"
  ],
  "license": "MIT",
  "main": "./dist/sra.js",
  "module": "./esm/sraAPI.js",
  "types": "./esm/sraAPI.d.ts",
  "devDependencies": {
    "typescript": "^3.1.1",
    "rollup": "^0.66.2",
    "rollup-plugin-node-resolve": "^3.4.0",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "uglify-js": "^3.4.9"
  },
  "homepage": "https://github.com/azure/azure-sdk-for-js",
  "repository": {
    "type": "git",
    "url": "https://github.com/azure/azure-sdk-for-js.git"
  },
  "bugs": {
    "url": "https://github.com/azure/azure-sdk-for-js/issues"
  },
  "files": [
    "dist/**/*.js",
    "dist/**/*.js.map",
    "dist/**/*.d.ts",
    "dist/**/*.d.ts.map",
    "esm/**/*.js",
    "esm/**/*.js.map",
    "esm/**/*.d.ts",
    "esm/**/*.d.ts.map",
    "lib/**/*.ts",
    "rollup.config.js",
    "tsconfig.json"
  ],
  "scripts": {
    "build": "tsc && rollup -c rollup.config.js && npm run minify",
    "minify": "uglifyjs -c -m --comments --source-map \"content='./dist/sra.js.map'\" -o ./dist/sra.min.js ./dist/sra.js",
    "prepack": "npm install && npm run build"
  },
  "sideEffects": false
}


In my package.json file for my project
==============================
{
	"name": "sraweb",
	"version": "1.0.0",
	"license": "MIT",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"serve": "npm run start -- --port 60518 --base-href=/SraWebCore/",
		"build": "ng build",
		"build:production": "npm run build -- --prod",
		"build:ssr": "npm run build --app=ssr --output-hashing=media",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e"
	},
	"private": true,
	"dependencies": {
		"@angular/animations": "^7.0.3",
		"@angular/common": "^7.0.3",
		"@angular/compiler": "^7.0.3",
		"@angular/core": "^7.0.3",
		"@angular/forms": "^7.0.3",
		"@angular/http": "^7.0.3",
		"@angular/platform-browser": "^7.0.3",
		"@angular/platform-browser-dynamic": "^7.0.3",
		"@angular/platform-server": "^7.0.3",
		"@angular/router": "^7.0.3",
		"@fortawesome/fontawesome-free": "^5.5.0",
		"@ng-bootstrap/ng-bootstrap": "^4.0.0",
		"@nguniversal/module-map-ngfactory-loader": "^7.0.2",
		"@okta/okta-angular": "^1.0.7",
		"angular": "^1.7.5",
		"aspnet-prerendering": "^3.0.1",
		"babel-polyfill": "^6.26.0",
		"bootstrap": "^4.1.3",
		"core-js": "^2.5.7",
		"guid-typescript": "^1.0.9",
		"lodash": "^4.17.11",
		"@azure/ms-rest-js": "^1.1.0",
		"@azure/ms-rest-azure-js": "^1.1.0",
		"ngx-bootstrap": "^3.1.1",
		"oidc-client": "^1.5.4",
		"rxjs": "^6.3.3",
		"stacktrace-js": "^2.0.0",
		"zone.js": "^0.8.26"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "^0.10.5",
		"@angular/cli": "^7.0.5",
		"@angular/compiler-cli": "^7.0.3",
		"@angular/language-service": "^7.0.3",
		"@types/jasmine": "^2.8.11",
		"@types/jasminewd2": "^2.0.6",
		"@types/node": "^10.12.7",
		"codelyzer": "^4.5.0",
		"jasmine-core": "~3.3.0",
		"jasmine-spec-reporter": "~4.2.1",
		"karma": "^3.1.1",
		"karma-chrome-launcher": "~2.2.0",
		"karma-coverage-istanbul-reporter": "^2.0.4",
		"karma-jasmine": "^1.1.2",
		"karma-jasmine-html-reporter": "^1.4.0",
		"protractor": "~5.4.1",
		"ts-node": "~7.0.1",
		"tslint": "~5.11.0",
		"typescript": "^3.1.6"
	}
}

And this is my import statement
=====================
import { TokenCredentials } from '@azure/ms-rest-js';

**Comment by amarzavery** [comment]
I believe you will have to use the browser bundle. Take a look at [this sample](https://github.com/Azure/ms-rest-js/blob/master/samples/index.html#L6) which includes the msRestBundle.js file and then instantiates the token credentials off it.

I believe `import { TokenCredentials } from '@azure/ms-rest-js';` would give you the node.js version.

**Comment by amarzavery** [comment]
os cannot be resolved because os is a node.js standard module. How will that be available in the browser?

**Comment by amarzavery** [comment]
os is defined as external in rollup.config.js. By following the explanation provided in the rollup documentation over [here](https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency), we may have to use [this plugin](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) for `import * as os from "os"` to work in node and browser.

**Comment by amarzavery** [comment]
@adha-admin - One more interesting thing to note:

> What the error relates to is the fact that the "os" cannot be resolved.
> ERROR in ./node_modules/@azure/ms-rest-js/es/lib/policies/msRestUserAgentPolicy.js
Module not found: Error: Can't resolve 'os' in 'D:\x\git\Projects\sra\src\sra.web\ClientApp\node_modules@azure\ms-rest-js\es\lib\policies'

You are using this with Angular that is supposed to be used in the browser. However the code is using the file `(msRestUserAgentPolicy.js)` that should be used for node.js environment rather than the browser one `msRestUserAgentPolicy.browser.js`.

@daschult 
I think, [this line in package.json](https://github.com/Azure/ms-rest-js/blob/master/package.json#L44)
is the culprit. 
```json5
"./es/lib/policies/telemetry/msRestUserAgentPolicy.js": "./es/lib/policies/telemetry/msRestUserAgentPolicy.browser.js"
```

It is pointing to a file that does not exist at that location. It should rather be something like this

remove the telemetry folder from the path for both the files.
```json5
"./es/lib/policies/msRestUserAgentPolicy.js": "./es/lib/policies/msRestUserAgentPolicy.browser.js"
```

@adha-admin - Can you make the above change in `node_modules/@azuree/ms-rest-js/package.json` file and try again? Let us know if that solves the problem

**Comment by adha-admin** [comment]
GREAT !
That change in the package.json file as fixed the issue.
"./es/lib/policies/telemetry/msRestUserAgentPolicy.js": "./es/lib/policies/telemetry/msRestUserAgentPolicy.browser.js"
to
"./es/lib/policies/msRestUserAgentPolicy.js": "./es/lib/policies/msRestUserAgentPolicy.browser.js"
I presume this will go in the next release?

**Comment by daschult** [comment]
Yes, it will. Thanks @amarzavery for catching this.

**Comment by adha-admin** [comment]
Thanks guys,
Please let me know when you have published this fix and what the version is.

**Comment by amarzavery** [comment]
@adha-admin - New version (1.2.1) of @azure/ms-rest-js has been published to npm.
