### ISSUE TITLE
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by SaifAsad** [Azure/ms-rest-js#290]
**Is your feature request related to a problem? Please describe.**
Using this library with 'Creact React App' is causing an error when the isolatedModules flag is set to true.
Due to a limitation in CRA (whcih has just started supporting typescript), isolatedModules flag cannot be changed to false. 

The error is caused by the way enums are declared in lib/url.ts

declare **const** enum URLTokenizerState 
declare **const** enum URLTokenType

**Describe the solution you'd like**
removing 'const' from enum declaration should resolve the issue:

declare enum URLTokenizerState 
declare enum URLTokenType

**Describe alternatives you've considered**
Would love to get suggestions on alternatives other than changing the library in node modules.

**Additional context**

According to [this](https://stackoverflow.com/a/28818850/5063433) brilliant SOF answer,
'const' keyword is not required in this case since the enum members are not computed,
which means that the references to the enum are not going to be inlined regardless if const is provided or not.

Happy to submit PR for this, if the issue is accepted,

Many thanks.

**Comment by daschult** [comment]
Thanks for the perfect issue. I've created a PR to resolve.

**Comment by daschult** [comment]
Blocked by https://github.com/Azure/ms-rest-js/issues/293.

**Comment by daschult** [comment]
[This version of @azure/ms-rest-js](https://www.npmjs.com/package/@azure/ms-rest-js/v/1.2.2) should solve this problem.
