### ISSUE TITLE
TypeError: this.getPackageJsonInfo is not a function

### ISSUE THREAD

**Issue by whyleee** [Azure/ms-rest-js#3]
I'm trying to load generated javascript by Autorest in the browser using "ms-rest-js" module instead of node.js specific "ms-rest". I get `TypeError: this.getPackageJsonInfo is not a function` when trying to call generated api client constructor in these lines (see [Autorest node.js generated client sample](https://github.com/Azure/autorest/blob/master/Samples/1b-code-generation-multilang/NodeJS/swaggerPetstore.js#L404)):

```
let packageInfo = this.getPackageJsonInfo(__dirname);
this.addUserAgentInfo(`${packageInfo.name}/${packageInfo.version}`);
```

As I understand this is because my client code is generated by newer Autorest versions which "ms-rest-js" doesn't support yet. I see that [testClient.ts](https://github.com/Azure/ms-rest-js/blob/master/test/data/TestClient/lib/testClient.ts) file in this repo was generated by Autorest 0.14.0, but I can't understand how to generate my client using this old version. Autorest `--version` parameter only supports versions from `1.0.1` and even installing Autorest 0.14.0 from npm doesn't help - it automatically downloads and uses the latest version or fails with `--version=0.14.0` parameter: `AutoRest version '0.14.0' is not found in the releases feed.`

Is it possible to generate api client with some old Autorest version that is supported by "ms-rest-js"?

**Comment by amarzavery** [comment]
You need to use the [typescript generator](https://www.npmjs.com/package/@microsoft.azure/autorest.typescript). The generated client for typescript is a little different than the node.js client generated by Autorest.
`autorest --typescript --output-folder="Your output folder" --license-header=MICROSOFT_MIT_NO_VERSION --input-file="Your swagger spec.json" --package-name="your-package-name" --package-version="0.1.0" --generate-metadata=true`

When you use the `--generate-metadata=true` switch it will generate package.json, webpack.config.js and tsconfig.json along with the generated client. Then execute `npm install` and `npm run build`. That will give you the browser version.

Let me know if you there are any issues.

**Comment by amarzavery** [comment]
@whylee - Are you unblocked?

**Comment by whyleee** [comment]
Sorry for delay. I'm trying to generate the code with typescript generator, but I'm stuck with this error:
```
>  autorest --input-file=swagger.json --typescript --output-folder=ts --package-name="test-api" --package-version="0.1.0" --generate-metadata=true
```
```
Error: Cannot resolve pipeline stage 'swagger-document/identity'.
    at resolvePipelineStageName (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:135:15)
    at inputs.map (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:152:108)
    at Array.map (<anonymous>)
    at createNodesAndSuffixes (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:152:97)
    at BuildPipeline (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:198:9)
    at Object.<anonymous> (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:207:26)
    at Generator.next (<anonymous>)
    at C:\Users\pavel\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:17:75
    at Promise (<anonymous>)
    at global.__awaiter (C:\Users\pavel\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:13:16)
    at Object.RunPipeline (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:206:12)
    at AutoRest.<anonymous> (C:\Users\pavel\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\autorest-core.js:173:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\pavel\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Autorest is trying to read my "readme.md" file configuration, which I copied from [typescript generator readme](https://github.com/Azure/autorest.typescript#autorest-extension-configuration). Maybe I'm doing something wrong, but I can't find any related docs in the web or github how to correctly use typescript plugin.

**Comment by amarzavery** [comment]
@whylee - Sorry for the delayed response. We had some updates going on in core autorest. The installation has been made super simple now.
Please make sure that the version of node.js on your system is atleast 7.10 or greater. Feel free to install the latest version in the 8.x range. After that
- `npm install -g autorest@preview`
- `autorest --output-folder=<path-to-output-folder> --package-name=<your-package-name> --typescript <path-to-swagger-spec/readme.md> --generate-metadata=true --package-version=<package-name>`
**OR direct path to the swagger spec using --input-file=<>**, if there is no markdown configuration
- `autorest --output-folder=<path-to-output-folder> --package-name=<your-package-name> --typescript --input-file=<path-to-swagger-spec.json> --generate-metadata=true --package-version=<package-name>`

**Comment by whyleee** [comment]
Finally get it to work, thanks! `--generate-metadata=true` option doesn't produce any additional files though, so I build TypeScript files with webpack to plain JavaScript.

**Comment by amarzavery** [comment]
Glad to know that you are unblocked. Interesting. I tested it yesterday and was able to generate package.json, webpack.config.js and tsconfig.json. Essentially these files contain static data which is more or less similar to the ones present in this repo. Feel free to open more issues if you see further problems.

**Comment by amarzavery** [comment]
@whylee 
> --generate-metadata=true option doesn't produce any additional files though

What is the path to --output-folder=<> ? Is it something like `C:\ts` i.e. is it a top level directory in your drive? May be that could be an issue.
Try giving something like `"C:\ts\lib"` and then use --generate-metadata=true. The 3 files tsconfig.json, package.json and webpack.config.js are usually one level up. If the path to output-folder was a top level directory then the program may not be able to write files.

**Comment by whyleee** [comment]
You are right, autorest generates these files in the upper directory. I didn't even think to look up there :smile: I think this option should either create the files in the current directory or get path value instead of bool. Creating files in the parent directory is very confusing as for me.

Thanks for your help, now I know how to generate browser javascript and can continue testing it.

**Comment by amarzavery** [comment]
Thanks for the feedback. I will look into this. I was under the assumption that user would usually give the path to the src or lib folder of the project as that is where you would want the generated client source code to be. Usually we have the package.json and tsconfig.json etc. files in the root of the project. But you are right, may be asking the filepath for the metadata would be easier.
