### ISSUE TITLE
Add documentation how to use `loginWithAppServiceMSI` in typescript

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/ms-rest-js#305]
**Is your feature request related to a problem? Please describe.**
I try to use the `loginWithAppServiceMSI` in my typescript code.  The documentation at [npmjs](https://www.npmjs.com/package/@azure/ms-rest-nodeauth#msi-managed-service-identity-based-login-from-an-appservice-or-azure-function-created-in-azure) loads the `msRestNodeAuth` from `../lib/msRestNodeAuth`. This does not work in the typescript compiler.

**Describe the solution you'd like**
Add documentation how a MSI Token should get with typescript.

**Describe alternatives you've considered**
Stay at the old libs.

**Comment by ngrewe** [comment]
The functionality seems to have moved to the [@azure/ms-rest-nodeauth](https://github.com/Azure/ms-rest-nodeauth). The following import works for me:

```ts
import { loginWithAppServiceMSI, MSIAppServiceOptions } from '@azure/ms-rest-nodeauth';
```

**Comment by kpajdzik** [comment]
@ngrewe is correct. Whole Node.js authentication story for moved to @azure/ms-rest-nodeauth project and browser authentication can be found in @azure/ms-rest-browserauth project.

**Comment by StefanSchoof** [comment]
Sorry for reporting to the wrong repro. I followed a wrong link and did not check, see https://github.com/Azure/ms-rest-nodeauth/issues/48.
