### ISSUE TITLE
Expose or enable keep-alive/userAgent configuration 

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/ms-rest-js#308]
**Is your feature request related to a problem? Please describe.**

Hi @daschult,

This is a feature request from @azure/storage-blob|file|queue regarding keep-alive configuration.

In our performance testing in Node.js runtime, after enabling keep-alive (by modifying axiosHttpClient provided ms-rest-js), the performance gains really lots. For high frequency queue message operations, the performance can be improved 3 times by enabling keep-alive. This feature is very important for storage scenarios especially for high performance required users.

However, ms-rest-js's default axiosHttpClient implementation doesn't expose this option.

**Describe the solution you'd like**

Best choice is to let ms-rest-js expose the keep-alive configuration or Http(s)Agent configuration.
Another candidate choice is to make default HTTP client enabling keep-alive.

**Describe alternatives you've considered**

**Additional context**

**Comment by daschult** [comment]
Hi @XiaoningLiu. What changes did you do to enable keepAlive on the axios client? Can you send a pull request to ms-rest-js or just paste your axiosHttpClient.ts code here?

**Comment by XiaoningLiu** [comment]
Hi @daschult  There are 2 choices. 1st one is simple, 2nd is more flexible, both fit our needs.

1. Enable keep-alive by default

https://github.com/Azure/ms-rest-js/blob/d661d0d98dadf4bd7c4dd7ec8604bd0d8af62827/lib/axiosHttpClient.ts#L14

Update to:

```javascript
const axiosClient = axios.create({
  httpAgent: new http.Agent({ keepAlive: true }),
  httpsAgent: new https.Agent({ keepAlive: true }),
});
```

This will enable keep-alive for the axiosClient instance.

2. Expose httpAgent and httpsAgent options into `httpRequest: WebResource`. Then

https://github.com/Azure/ms-rest-js/blob/d661d0d98dadf4bd7c4dd7ec8604bd0d8af62827/lib/axiosHttpClient.ts#L122

```javascript
      const config: AxiosRequestConfig = {
        method: httpRequest.method as any,
        url: httpRequest.url,
        headers: rawHeaders,
        data: axiosBody,
        transformResponse: undefined,
        validateStatus: () => true,
        // Workaround for https://github.com/axios/axios/issues/1362
        maxContentLength: Infinity,
        responseType: httpRequest.streamResponseBody ? "stream" : "text",
        cancelToken,
        timeout: httpRequest.timeout
      };
      res = await axiosClient(config);
```

Could add following 2 options into the `config`:

```javascript
  httpAgent: httpRequest.httpAgent,
  httpsAgent: httpRequest.httpsAgent,
```

This needs autorest.typescript generator support httpAgent and httpsAgent, e.g in `RequestOptionsBase`.

**Comment by daschult** [comment]
Thanks so much @XiaoningLiu. @kpajdzik, can you implement @XiaoningLiu's first suggestion?

**Comment by XiaoningLiu** [comment]
Hi @kpajdzik, what's the progress?

**Comment by kpajdzik** [comment]
@XiaoningLiu, Axios 0.19 is going to be released soon and it is going to be much easier to make Keep-Alive work without impacting any team. We're going to wait for the release with this task.

Axios task with release tracking: https://github.com/axios/axios/issues/1657

**Comment by XiaoningLiu** [comment]
Hi @kpajdzik What's the blocker to add keep-alive support before axios 0.19.0?

axios still doesn't release 0.19 for such a long time, and not sure how long it will take. We recently got more and more customers complaining about the new storage SDK performance and timeout issues due to this. Some customers switched to our legacy storage SDK which enables keep-alive by default.

**Comment by kpajdzik** [comment]
Done in the latest version of ms-rest-js (using node-fetch)
