### ISSUE TITLE
Consider Standardizing on fetch for Rest Calls

### ISSUE THREAD

**Issue by justinwilaby** [Azure/ms-rest-js#310]
The discussion at #8 addresses several issues that can be solved by standardizing on `fetch` for the browser and `node-fetch` for node. 
 
✓ Proxy support 
✓ FormData Support
✓ Standard API
✓ Zero dependencies for the web
✓ Reasonable number of dependencies for Node
✓ Isomorphic

**Comment by RikkiGibson** [comment]
I wanted to note why we didn't end up using fetch as the person who was responsible for us moving away from it. (no longer working on the project)

- node-fetch didn't have abort support
- fetch implementations didn't have support for progress reporting (particularly useful for file uploads)

I'm sure these issues will be rectified eventually at which point the maintainers may revisit the question.

**Comment by justinwilaby** [comment]
Looks like [Abort support](https://github.com/bitinn/node-fetch/blob/master/README.md#request-cancellation-with-abortsignal) was already added.

Since `node-fetch` can post using [file streams](https://github.com/bitinn/node-fetch#post-data-using-a-file-stream), it seems reasonable that upload progress can be achieved using the [data event](https://nodejs.org/api/stream.html#stream_event_data). This might also be available using the [web-api for ReadableStreams](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#Examples) as well.

**Comment by ramya-rao-a** [comment]
`@azure/ms-rest-js` is currently in maintenance mode with no new features being added and taking only bug fixes. We are moving active development efforts in the azure-sdk-for-js repo on `@azure/core-http` that will power the next generation of the Azure packages which is using node-fetch and the standardized `@azure/abort-controller`. Therefore, closing this issue.
