### ISSUE TITLE
`abortSignal` option should be named `signal` like Fetch.

### ISSUE THREAD

**Issue by bterlson** [Azure/ms-rest-js#339]
When using `fetch` in the browser, one passes the abort signal into fetch using the option `signal`:

```
fetch(url, {signal})
```

However, ms-rest-js calls this option abortSignal. While I like abortSignal better as a name, I wonder if we should align with the platform so things are named what people are used to.

/cc @ramya-rao-a

**Comment by amarzavery** [comment]
Changing the name from abortSignal to signal will cause breaking changes. I know storage uses this feature, currently. Just wanted to ensure this aspect is considered, whenever the decision is made.

**Comment by bterlson** [comment]
@amarzavery good to call out. Just curious, do you prefer:

1. Change nothing
2. Continue using `abortSignal` in Storage, use `signal` everywhere else
3. Change to `signal` everywhere

**Comment by amarzavery** [comment]
I am more inclined towards option 1.

I think, storage is exposing this option to the end user, not 100% sure. `abortSignal` is also one of the options in the RequestPrepareOptions which is provided as a part of optional parameters for all the generated methods in the sdk. Thus it would be a breaking change for all the management plane sdks too. _Although all the new JS management plane sdks are in preview and i am not sure how many people are using the request cancellation feature_.

Is it worth the benefit? 

@kpajdzik @daschult - what are your thoughts?

**Comment by daschult** [comment]
I prefer the `abortSignal` name just because it indicates what the signal is for. `signal` doesn't tell you what it is for at all. It's unfortunate that the community has already accepted `signal`, but I don't think there are any large benefits to changing the property's name. There are definite downsides (forcing existing customers to update their code that integrates with our packages), but I don't think this enables us to do more than we already were.

**Comment by ramya-rao-a** [comment]
`@azure/ms-rest-js` is currently in maintenance mode with no new features being added and taking only bug fixes. We are moving active development efforts in the azure-sdk-for-js repo on `@azure/core-http` that will power the next generation of the Azure packages. Therefore, closing this issue.
