### ISSUE TITLE
Breaking minor version change: @azure/ms-rest-js 1.8.2 -> 1.8.4

### ISSUE THREAD

**Issue by daveta** [Azure/ms-rest-js#346]
**Package Version**: 1.8.2 => 1.8.4
- [X] **nodejs**

**Describe the bug**
From version 1.8.2 to 1.8.4, we get the following error:
error TS2345: Argument of type 'TokenCredentials' is not assignable to parameter of type 'ServiceClientCredentials'.  Types of property 'signRequest' are incompatible.

**Expected behavior**
Minor version changes should not cause breaks.  We need to be following [semver](https://semver.org/).

**Screenshots**
![image](https://user-images.githubusercontent.com/6182197/57560841-61a65200-733d-11e9-83eb-db731857f730.png)

**Additional context**
https://github.com/microsoft/botbuilder-js/issues/916
https://github.com/microsoft/botbuilder-js/pull/922/files

**Comment by amarzavery** [comment]
@kpajdzik - Can you take a look at this?

**Comment by kpajdzik** [comment]
Synced up with Dave offline, we haven't introduced any breaking changes in the latest ms-rest-js.
