### ISSUE TITLE
ChangeLog.md is not updated

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/ms-rest-js#348]
Hi,

ChangeLog.md seems not fully updated with npm released versions, and doesn't include all release changes. Is this by purpose?

https://github.com/Azure/ms-rest-js/blob/master/Changelog.md
https://www.npmjs.com/package/@azure/ms-rest-js

**Comment by amarzavery** [comment]
Fixed via #349 Here is the updated [changelog](https://github.com/Azure/ms-rest-js/blob/master/Changelog.md)
