### ISSUE TITLE
Add typings or index.d.ts to the library

### ISSUE THREAD

**Issue by PrashanthCorp** [Azure/ms-rest-js#363]
In some cases, we want to make enforce types on responses or callback variables. I noticed for eg., that the HttpOperationResponse interface is exported. However, every site where the interface is imported references the file directly, which tells me that a user of the library should not assume they can use the types. 

**Describe the solution you'd like**
Having an index.d.ts would help me understand what types I can and cannot use.

**Describe alternatives you've considered**
I currently refer to specific fields which I use. Here's the current usage - 
https://github.com/microsoft/vscode-cosmosdb/blob/351180b1e8016853e82306d1b7d3083fe333e123/src/graph/gremlinEndpoints.ts#L21
That block can just be typed, and I would not have to enunciate what specific fields I expect.

**Comment by RikkiGibson** [comment]
It's there in the distributed package: https://unpkg.com/@azure/ms-rest-js@1.8.13/es/lib/msRest.d.ts

It might be good to align with conventions by naming it index.d.ts, but it's referenced in the conventional way in the package.json "types" property, so it's definitely discoverable.
