### ISSUE TITLE
Out of memory issue on making hundreds of requests

### ISSUE THREAD

**Issue by aby040** [Azure/ms-rest-js#374]
**Package Version**: 1.8.13
- [x] **nodejs**
   - **nodejs version**: 10.16.0
   - **os name/version**: macOS Catalina
- [ ] **browser**
    - **name/version**: ____

**Describe the bug**
Out of memory issue on making multiple requests to fetch the list of `network-interfaces` using the `@azure/arm-network` package (version 14.0.0)

**To Reproduce**
1. Try to make hundreds of request to fetch the list of `network-interfaces` using the `@azure/arm-network` package (version 14.0.0).
2. Increase in the heap size can be observed after each request which is not getting cleared.

**Expected behavior**
There should not be any memory leak.

**Additional context**
Issue is not found on later versions of `@azure/arm-network` but there are other `@azure` packages which are still relying on versions `^1.8.1` of `@azure/ms-rest-js`

**Comment by ramya-rao-a** [comment]
Fixed with #375
