### ISSUE TITLE
Stop polluting the global namespace with fetch

### ISSUE THREAD

**Issue by aaomidi** [Azure/ms-rest-js#383]
https://github.com/Azure/ms-rest-js/blob/6244e919cf78268e20e173afd1b320633c016a68/lib/nodeFetchHttpClient.ts#L18

As a self-contained library, doing this can cause havoc on other users. Lots of dual browser and node libraries check the global namespace for fetch before defaulting to requiring.

This code is essentially forcing its own flavor of node-fetch onto everything else that follows that same practice.

It shouldn't be necessary to pollute the global namespace like this.

**Comment by xirzec** [comment]
Seems like we could port https://github.com/Azure/azure-sdk-for-js/pull/9880
