### ISSUE TITLE
HttpOperationResponse.readableStreamBody always null

### ISSUE THREAD

**Issue by ropnop** [Azure/ms-rest-js#393]
**Package Version**: 2.0.4
- [x ] **nodejs**
   - **nodejs version**: 12.15
   - **os name/version**: OSX 10.14.6

**Describe the bug**
When using ServiceClient to send a request, the HTTPOperationResponse always has readableStreamBody set to null. I am trying to use the ServiceClient to download a large storage blob, and it always converts the entire body to a string, and won't let me use the readable stream to pipe to a file.

**To Reproduce**
Here's a snippet  example of what I'm trying to do:
```ts
const creds = await AzureCliCredentials.create({
    resource: "https://storage.azure.com"
});
const client = new ServiceClient(creds);
const request: RequestPrepareOptions = {
            url: "https://example.blob.core.windows.net/example/myblob.tar.gz",
            method: "GET",
            headers: {"X-Ms-Version":"2018-11-09"},
};
const res = await client.sendRequest(request)
await new Promise((resolve, reject) => {
            const writeStream = fs.createWriteStream(path)
            .on('error', reject)
            .on('close', resolve)

            res.readableStreamBody!.pipe(writeStream)
            .on('error', reject)
})
```

**Expected behavior**
I would expect res.readableStreamBody to not be null and the large response body to be piped to the outputFile. Instead readableStreamBody is null and nothing is piped

**Additional context**
I may be missing something, but have been reading through all the docs and trying to find examples, but can't figure out why readableStreamBody is null

**Comment by xirzec** [comment]
I believe the `@azure/storage-blob` supports this functionality:

https://www.npmjs.com/package/@azure/storage-blob

**Comment by jeremymeng** [comment]
@ropnop we need to set `streamResponseBody` to true on the request to stream response body. Could you please try the following code?

```typescript
 const request = new msRest.WebResource(
   "https://example.blob.core.windows.net/example/myblob.tar.gz", // url
   "GET", // method
   undefined, // body
   undefined, // query
   new msRest.HttpHeaders({"X-Ms-Version":"2018-11-09"}), // headers
   true // streamResponseBody
 );

 client.sendRequest(request).then(function (res: msRest.HttpOperationResponse) {
  // omitted
 });

```

**Comment by bwateratmsft** [comment]
I've found the issue; [WebResource.prepare](https://github.com/Azure/ms-rest-js/blob/master/lib/webResource.ts#L275) does not copy `streamResponseBody`. I'm going to make a PR to fix it.
