### ISSUE TITLE
ThrottlingRetryPolicy only retries once

### ISSUE THREAD

**Issue by joheredi** [Azure/ms-rest-js#394]
See Azure/azure-sdk-for-js/issues/7989 for details

>  FWIW, the API answers a 429 response which the ThrottlingRetryPolicy handles once with a retry, but when that also returns a 429, it doesn't try again. The API says Retry-After 17, but the request is still rejected with a 429 and another Retry-After 17. I wish the API would return a time that is more likely to work out. That is, I would have liked to see the API drive the retries, so that we could easily burst under 100 requests and throttle back based on meaningful responses from the API. Instead, I'm going to have to use p-throttle to proactively throttle and spread 100 requests out over 5 minutes.

**Comment by jeremymeng** [comment]
We could retry more on 429.  Some design questions to consider
- should we provide an option to specify the max retry count
- what value should be the default for max retry count
   - infinite/max integer value, or some small number

**Comment by jeremymeng** [comment]
Fixed by #417. Closing
