### ISSUE TITLE
node-sample.js is not a file in dir sample

### ISSUE THREAD

**Issue by Vijendra07Kulhade** [Azure/ms-rest-js#399]
**Package Version**: _______
- [x] **nodejs**
   - **nodejs version**:  12.0.0
   - **os name/version**: macOS Cataline version 10.15.6

**Describe the bug**
Tried running `node samples/node-sample.js` as mentioned in the readme. But it seems file itself is not available.
**To Reproduce**
1. `git clone https://github.com/Azure/ms-rest-js.git`
2. Set Subscription ID and Access Token
3. Run `node samples/node-sample.js`
**Expected behavior**
It should login to the account and print the response body.
**Screenshots**

**Additional context**

**Comment by xirzec** [comment]
Could try `npx ts-node samples/node-sample.ts`

**Comment by jeremymeng** [comment]
Fixed by #411. Closing.
