### ISSUE TITLE
KeepAlive property is not cloned

### ISSUE THREAD

**Issue by martinsamanek** [Azure/ms-rest-js#405]
When using WebResource clone function, keepAlive property is not cloned

https://github.com/Azure/ms-rest-js/blob/01cfc78e2fe58d376cf1398f758d6e34415864c8/lib/webResource.ts#L418

**Comment by daviwil** [comment]
@joshgummersall could you possibly also include a fix for this in the 2 PRs you have out?  Should just be a matter of making sure `keepAlive` gets assigned in the `clone` function.

**Comment by joshgummersall** [comment]
Included in both 2.x and 1.x
