### ISSUE TITLE
systemErrorRetryPolicy doesn't do anything

### ISSUE THREAD

**Issue by ejizba** [Azure/ms-rest-js#412]
I noticed the "ms-rest-js" package has the same exact problem the "core-http" package had as described here:

https://github.com/Azure/azure-sdk-for-js/pull/8803
https://github.com/Azure/azure-sdk-for-js/issues/8459

Since it doesn't use `catch` and pass an `error` along [here](https://github.com/Azure/ms-rest-js/blob/abc4f8f58ef1ac999315877eaf740c2bd0eddcbe/lib/policies/systemErrorRetryPolicy.ts#L58), it doesn't do anything.

I'm not super familiar with the differences between "ms-rest-js" and "core-http" - any idea why they have duplicate code in the first place?

**Comment by jeremymeng** [comment]
> I'm not super familiar with the differences between "ms-rest-js" and "core-http" - any idea why they have duplicate code in the first place?

Here's some context https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/core/core-https/documentation/core2.md#history-context-and-motivations

We should port the fix https://github.com/Azure/azure-sdk-for-js/pull/8803 here.

**Comment by ejizba** [comment]
@jeremymeng any idea when we can get an updated package with this fix? This has been a thorn in our side for a while and it's a pretty wide-ranging problem for us. I work on Azure extensions for VS Code, and it seems like pretty much every `@azure/arm-*` package we use relies on "ms-rest-js", not "core-http"

**Comment by jeremymeng** [comment]
@ejizba I will work on porting the fix today, and hopefully have a release soon.

**Comment by jeremymeng** [comment]
Closing, fixed by #413
