### ISSUE TITLE
Version 1.11.0 missing @azure/core-auth

### ISSUE THREAD

**Issue by redjab** [Azure/ms-rest-js#428]
**Package Version**: 1.11.0
- [ ] **nodejs**
   - **nodejs version**: 14
   - **os name/version**: Windows 10
- [ ] **browser**
    - **name/version**: ____

**Describe the bug**

Error: ./node_modules/@azure/ms-rest-js/es/lib/serviceClient.js
Module not found: Error: Can't resolve '@azure/core-auth' in '\node_modules\@azure\ms-rest-js\es\lib'
resolve '@azure/core-auth' in '\node_modules\@azure\ms-rest-js\es\lib'

@azure/core-auth is being listed in this version as a dev dependency instead of a dependency.

**Comment by jeremymeng** [comment]
Should be fixed in v1.11.2 now.  Closing
