### ISSUE TITLE
Support NO_PROXY environment variable

### ISSUE THREAD

**Issue by chrmarti** [Azure/ms-rest-js#439]
**Is your feature request related to a problem? Please describe.**

Debugged a proxy issue with a customer and it turned out that they have to rely on `NO_PROXY` being available to fully configure their network requirements.

**Describe the solution you'd like**

Similar to the environment variables `HTTP_PROXY` and `HTTPS_PROXY`, `NO_PROXY` should be supported.

**Describe alternatives you've considered**

The customer and I found a workaround and I have since found a fix to include in our own code, but I still wanted to report this issue here. (https://github.com/microsoft/vscode/issues/117054)

**Additional context**

None.

**Comment by jeremymeng** [comment]
Fixed by #441

**Comment by jeremymeng** [comment]
This is now supported in released v2.3.0.
