### ISSUE TITLE
Managing nested http client requests

### ISSUE THREAD

**Issue by fvassura** [Azure/ms-rest-js#452]
Hi all,
I am working on an Angular project that uses Autorest to map api libraries (C#) in typescript. 
Sorry if I ask something strange but I am a total newbie of this world.

We have a menu to navigate through different pages and usually each page on load starts making api calls to load data.

### PROBLEM
When we change page we want to stop previous pending requests.

We found out that you have an _AbortSignal_ property in your request object so we are trying to extend the BaseRequestPolicy to link every request to a common AbortService and then trigger Abort on Route changed endEvent.

Our Policy:
```typescript
export class AbortRequestPolicy extends BaseRequestPolicy {

  static abortPolicy(abortService: AbortService): RequestPolicyFactory {
    return {
      create: (nextPolicy: RequestPolicy, options: RequestPolicyOptions) => {
        return new AbortRequestPolicy(nextPolicy, options, abortService);
      }
    };
  }


  constructor(nextPolicy: RequestPolicy, options: RequestPolicyOptions, private abortService: AbortService) {
    super(nextPolicy, options);

  }

  async sendRequest(request: WebResource): Promise<HttpOperationResponse> {
    //console.log('[AbortPolicy]Dentro sendRequest');
    request.abortSignal = this.abortService?.signal;
    const response = await this._nextPolicy.sendRequest(request);

    return response;
  }

}
```

### QUESTION

 Is this the right way to do it or do you some better suggestions?

For example I found this way to manage piped observables:
[https://www.learnrxjs.io/learn-rxjs/operators/transformation/switchmap](https://www.learnrxjs.io/learn-rxjs/operators/transformation/switchmap)
Could I use this?

Thanks in advance

**Comment by jeremymeng** [comment]
@fvassura Let me try to understand your scenario.  The generated methods also take the abortSignal via options bag.  So you don't want to pass your signal to each individual API calls, and instead want to centralize it by using this request policy to add the signal for all the requests?

I think this is a valid use case of request policies. Adding our abortSignal expert @chradek: Chris do you have any insights?

> For example I found this way to manage piped observables:
> https://www.learnrxjs.io/learn-rxjs/operators/transformation/switchmap
> Could I use this?

I am afraid that I cannot comment on it as I am familiar with rxjs.

**Comment by fvassura** [comment]
Ok, we started using "centralized" abortSignal that we destroy and recreate on routeNavigationStart of a new page and it seems to work.
If you don't have better suggestions we will continue this way.

Thanks

**Comment by jeremymeng** [comment]
@fvassura glad to hear that it works.  I am closing this issue.  Feel free to contact us for further questions or feedback.
