### ISSUE TITLE
UUID deprication warning

### ISSUE THREAD

**Issue by AlexSpelt** [Azure/ms-rest-js#458]
- **Package Name**: 
@azure/ms-rest-js
- **Package Version**: 
- **Operating system**:
- [x] **nodejs**
    - **version**: 
- [ ] **browser**
    - **name/version**: 
- [ ] **typescript**
    - **version**:
- Is the bug related to **documentation** in
  - [ ] README.md
  - [ ] source code documentation
  - [ ] SDK API docs on https://docs.microsoft.com

**Describe the bug**
UUID version 3 is deprecated. version 7 is the minimum version. Please update the UUID version of this project. Right now I'm getting the following errors when doing a clean install.

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

it is caused by the following import

```JSON
"@azure/ms-rest-js": {
      "version": "2.1.0",
      "resolved": "https://registry.npmjs.org/@azure/ms-rest-js/-/ms-rest-js-2.1.0.tgz",
      "integrity": "sha512-4BXLVImYRt+jcUmEJ5LUWglI8RBNVQndY6IcyvQ4U8O4kIXdmlRz3cJdA/RpXf5rKT38KOoTO2T6Z1f6Z1HDBg==",
      "requires": {
        "@types/node-fetch": "^2.3.7",
        "@types/tunnel": "0.0.1",
        "abort-controller": "^3.0.0",
        "form-data": "^2.5.0",
        "node-fetch": "^2.6.0",
        "tough-cookie": "^3.0.1",
        "tslib": "^1.10.0",
        "tunnel": "0.0.6",
        "uuid": "^3.3.2",
        "xml2js": "^0.4.19"
      },
      "dependencies": {
        "uuid": {
          "version": "3.4.0",
          "resolved": "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz",
          "integrity": "sha512-HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A=="
        }
      }
```

**To Reproduce**
1. install project with `npm ci`

**Expected behavior**
a clean install without deprication warnings

**Comment by AlexSpelt** [comment]
@ramya-rao-a 

The import comes from @azure/storage-blob. I've pasted the import from package.json. The snippet above is from package-lock.json.

```JSON
"@azure/storage-blob": "^10.5.0"
```

in package-lock.json, I've got the following import of ms-rest-js.

```JSON
"node_modules/@azure/storage-blob": {
      "version": "10.5.0",
      "resolved": "https://registry.npmjs.org/@azure/storage-blob/-/storage-blob-10.5.0.tgz",
      "integrity": "sha512-67+0EP7STy9BQgzvN1RgmSvXhxRd044eDgepX7zBp7XslBxz8YGo2cSLm9w5o5Qf1FLCRlwuziRMikaPCLMpVw==",
      "dependencies": {
        "@azure/ms-rest-js": "^2.0.0",
        "events": "^3.0.0",
        "tslib": "^1.9.3"
      }
    }
```

**Comment by AlexSpelt** [comment]
@ramya-rao-a 

I thought I was using the latest version of @azure/storage-blob. But I wasn't. I've updated to the latest version v12 and there are no errors from the azure SDK anymore. MSSQL still has an import of an out-of-date tedious package. And I'm using the latest version from them.

But that issue does not fit in the context of the azure-sdk. Thanks for the help.

**Comment by ramya-rao-a** [comment]
Thanks for getting back to us on that @AlexSpelt !

While we have you here, can you share if there were any documentation that led you to using v10 of `@azure/storage-blob`? We would like to make sure such documentation gets updated.

**Comment by AlexSpelt** [comment]
I think I developed the azure storage implementation about 1 to 2 years ago. It has nothing to do with the documentation. I thought `npm install` updated packages. It only does that in a minor way.

But marking version 10 and all other versions that use deprecated packages, as deprecated, would have helped me find the root of the problem more quickly.

**Comment by ramya-rao-a** [comment]
Thanks for the feedback @AlexSpelt
