### ISSUE TITLE
Remove moment dependency

### ISSUE THREAD

**Issue by daschult** [Azure/ms-rest-js#47]

**Comment by amarzavery** [comment]
I have commented on a [long standing issue](https://github.com/moment/moment/issues/2373) in moment.js that requests them to modularize moment. I don't foresee that happening anytime soon. 

Worst case scenario, rip out the duration pieces from moment and put it in a separate repo and publish to npm as a separate package. That should definitely reduce the package size.

**Comment by amarzavery** [comment]
Do take a look at this library Luxon. It has pretty good duration support and it looks like webpack will only bundle duration parts based on what we import.
https://moment.github.io/luxon/docs/class/src/duration.js~Duration.html
