### ISSUE TITLE
SecurityType requirement from DomParser directly

### ISSUE THREAD

**Issue by Czhang0727** [Azure/ms-rest-js#470]
**Is your feature request related to a problem? Please describe.**
As Office org is moving to SecurityType, we are not allow to use DOMParser directly.
https://github.com/Azure/ms-rest-js/blob/23475a899c66d74d15d92c1a02bb9d0f7315d0a3/lib/util/xml.browser.ts#L19

Please consider move to SecurityTypeDomParser to avoid HTML inject.

**Describe the solution you'd like**

You can find some option here:
https://dev.azure.com/domoreexp/Teamspace/_wiki/wikis/NorthStar%20Docs/23760/trusted-types

**Describe alternatives you've considered**

**Additional context**

**Comment by jeremymeng** [comment]
@Czhang0727 thanks for reporting this issue!  Could you please tell us how you are using ms-rest-js? as a direct dependency, or indirectly via other packages?

**Comment by jeremymeng** [comment]
@Czhang0727 and do you have a link to the `SecurityTypeDomParser` mentioned above?

**Comment by dayday8421** [comment]
It appear this issue is the [same as one in azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js/issues/13268) which was resolved in [PR: 13382](https://github.com/Azure/azure-sdk-for-js/pull/13382)

**Comment by jeremymeng** [comment]
This has been addressed by #471
