### ISSUE TITLE
Bump Dependency On xml2js to Prevent Prototype Pollution

### ISSUE THREAD

**Issue by Kurt-von-Laven** [Azure/ms-rest-js#480]
**Package Version**: 2.6.4
- [x] **nodejs**
   - **nodejs version**: All
   - **os name/version**: All
- [x] **browser**
    - **name/version**: All

**Describe the bug**
`xml2js <= 0.4.23` contains [a recently disclosed high severity security vulnerability](https://github.com/advisories/GHSA-776f-qx25-q3cc). No patched version is available, and xml2js has not seen a release since 2019. The issue in xml2js is Leonidas-from-XIV/node-xml2js#663.

**To Reproduce**
1. Add a dependency on @azure/ms-rest-js.
2. Run `yarn npm audit --all --recursive`, or the equivalent command in your chosen package manager.

**Expected behavior**
No security vulnerabilities are detected.

**Additional context**
I suspect other `@azure` packages also depend on xml2js.

**Comment by Kurt-von-Laven** [comment]
xml2js 0.5.0 has been released, and the upstream issue has been closed as fixed, so a bump is probably all that is needed.

**Comment by jeremymeng** [comment]
v2.6.6 has been release with the fix from PR #481
