### ISSUE TITLE
Push polymorphic discriminator computation to the generator

### ISSUE THREAD

**Issue by daschult** [Azure/ms-rest-js#64]
In the latest implementation of `TypeSpecs`, we search the CompositeTypeSpec hierarchy for every operation when we need to match a provided value against the CompositeTypeSpec hierarchy. @amarzavery pointed out that we could push much of this computation to the generator.

**Comment by amarzavery** [comment]
Please refer to [this discussion in the PR](https://github.com/Azure/ms-rest-js/pull/63#discussion_r183194861) for more context.

**Comment by RikkiGibson** [comment]
Is this still a thing?

**Comment by daschult** [comment]
No.
