### ISSUE TITLE
Unable to set cookie header

### ISSUE THREAD

**Issue by ProTip** [Azure/ms-rest-js#89]
I'm dealing with a funky authentication process that requires me to:
1. Hit an endpoint with redirects set to 0 or handle all responses in the chain
2. Take the `Set-Cookie` header value from the first response and supply it with all future requests in the `Cookie` header

I'm attempting to accomplish this through a custom implementation of `ServiceClientCredentials` utilizing Axios(for now at least). For the life of me, whatever I try, the `cookie` header ends up blank on the wire. It appears some effort was made to get cookies working with fetch, however I can't get them working for myself :)

Any guidance on this would be much appreciated(or if I could convince you to utilize Axios :D ).

**Comment by RikkiGibson** [comment]
Which environment is the redirect failing in (nodejs or browser)?

Axios is something we've considered moving to under the hood due to some features we need not being available in the fetch polyfills yet.

**Comment by ProTip** [comment]
I'm currently testing with nodejs, however the redirect is not an issue as I'm handling that with Axios.

The issue I'm facing now is that after I set the `cookie` header in the `ServiceClientCredentials` implementation, the subsequent requests have no value for the `cookie` header; it has been cleared out. I have not attempted to get the cookie set naturally as it doesn't appear that `fetchHttpClient` is exported from the package.

**Comment by RikkiGibson** [comment]
My guess is that the runtime has been simply overwriting the Cookie header on the outgoing request based on what it thinks the cookie should be. I'll try and do something about this.
